/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PasswordFeedback - struct for PasswordFeedback
type PasswordFeedback struct {
	PasswordFeedbackOneOf *PasswordFeedbackOneOf
	PasswordFeedbackOneOf1 *PasswordFeedbackOneOf1
	String *string
}

// PasswordFeedbackOneOfAsPasswordFeedback is a convenience function that returns PasswordFeedbackOneOf wrapped in PasswordFeedback
func PasswordFeedbackOneOfAsPasswordFeedback(v *PasswordFeedbackOneOf) PasswordFeedback {
	return PasswordFeedback{
		PasswordFeedbackOneOf: v,
	}
}

// PasswordFeedbackOneOf1AsPasswordFeedback is a convenience function that returns PasswordFeedbackOneOf1 wrapped in PasswordFeedback
func PasswordFeedbackOneOf1AsPasswordFeedback(v *PasswordFeedbackOneOf1) PasswordFeedback {
	return PasswordFeedback{
		PasswordFeedbackOneOf1: v,
	}
}

// stringAsPasswordFeedback is a convenience function that returns string wrapped in PasswordFeedback
func StringAsPasswordFeedback(v *string) PasswordFeedback {
	return PasswordFeedback{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PasswordFeedback) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PasswordFeedbackOneOf
	err = newStrictDecoder(data).Decode(&dst.PasswordFeedbackOneOf)
	if err == nil {
		jsonPasswordFeedbackOneOf, _ := json.Marshal(dst.PasswordFeedbackOneOf)
		if string(jsonPasswordFeedbackOneOf) == "{}" { // empty struct
			dst.PasswordFeedbackOneOf = nil
		} else {
			if err = validator.Validate(dst.PasswordFeedbackOneOf); err != nil {
				dst.PasswordFeedbackOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PasswordFeedbackOneOf = nil
	}

	// try to unmarshal data into PasswordFeedbackOneOf1
	err = newStrictDecoder(data).Decode(&dst.PasswordFeedbackOneOf1)
	if err == nil {
		jsonPasswordFeedbackOneOf1, _ := json.Marshal(dst.PasswordFeedbackOneOf1)
		if string(jsonPasswordFeedbackOneOf1) == "{}" { // empty struct
			dst.PasswordFeedbackOneOf1 = nil
		} else {
			if err = validator.Validate(dst.PasswordFeedbackOneOf1); err != nil {
				dst.PasswordFeedbackOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PasswordFeedbackOneOf1 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PasswordFeedbackOneOf = nil
		dst.PasswordFeedbackOneOf1 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PasswordFeedback)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(PasswordFeedback): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(PasswordFeedback)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(PasswordFeedback): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(PasswordFeedback)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(PasswordFeedback): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(PasswordFeedback)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PasswordFeedback) MarshalJSON() ([]byte, error) {
	if src.PasswordFeedbackOneOf != nil {
		return json.Marshal(&src.PasswordFeedbackOneOf)
	}

	if src.PasswordFeedbackOneOf1 != nil {
		return json.Marshal(&src.PasswordFeedbackOneOf1)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PasswordFeedback) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PasswordFeedbackOneOf != nil {
		return obj.PasswordFeedbackOneOf
	}

	if obj.PasswordFeedbackOneOf1 != nil {
		return obj.PasswordFeedbackOneOf1
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PasswordFeedback) GetActualInstanceValue() (interface{}) {
	if obj.PasswordFeedbackOneOf != nil {
		return *obj.PasswordFeedbackOneOf
	}

	if obj.PasswordFeedbackOneOf1 != nil {
		return *obj.PasswordFeedbackOneOf1
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePasswordFeedback struct {
	value *PasswordFeedback
	isSet bool
}

func (v NullablePasswordFeedback) Get() *PasswordFeedback {
	return v.value
}

func (v *NullablePasswordFeedback) Set(val *PasswordFeedback) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordFeedback) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordFeedback) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordFeedback(val *PasswordFeedback) *NullablePasswordFeedback {
	return &NullablePasswordFeedback{value: val, isSet: true}
}

func (v NullablePasswordFeedback) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordFeedback) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


