/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.11.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PasswordFeedbackOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PasswordFeedbackOneOf1{}

// PasswordFeedbackOneOf1 struct for PasswordFeedbackOneOf1
type PasswordFeedbackOneOf1 struct {
	Toolong int32 `json:"toolong"`
}

type _PasswordFeedbackOneOf1 PasswordFeedbackOneOf1

// NewPasswordFeedbackOneOf1 instantiates a new PasswordFeedbackOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasswordFeedbackOneOf1(toolong int32) *PasswordFeedbackOneOf1 {
	this := PasswordFeedbackOneOf1{}
	this.Toolong = toolong
	return &this
}

// NewPasswordFeedbackOneOf1WithDefaults instantiates a new PasswordFeedbackOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordFeedbackOneOf1WithDefaults() *PasswordFeedbackOneOf1 {
	this := PasswordFeedbackOneOf1{}
	return &this
}

// GetToolong returns the Toolong field value
func (o *PasswordFeedbackOneOf1) GetToolong() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Toolong
}

// GetToolongOk returns a tuple with the Toolong field value
// and a boolean to check if the value has been set.
func (o *PasswordFeedbackOneOf1) GetToolongOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Toolong, true
}

// SetToolong sets field value
func (o *PasswordFeedbackOneOf1) SetToolong(v int32) {
	o.Toolong = v
}

func (o PasswordFeedbackOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PasswordFeedbackOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["toolong"] = o.Toolong
	return toSerialize, nil
}

func (o *PasswordFeedbackOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"toolong",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPasswordFeedbackOneOf1 := _PasswordFeedbackOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPasswordFeedbackOneOf1)

	if err != nil {
		return err
	}

	*o = PasswordFeedbackOneOf1(varPasswordFeedbackOneOf1)

	return err
}

type NullablePasswordFeedbackOneOf1 struct {
	value *PasswordFeedbackOneOf1
	isSet bool
}

func (v NullablePasswordFeedbackOneOf1) Get() *PasswordFeedbackOneOf1 {
	return v.value
}

func (v *NullablePasswordFeedbackOneOf1) Set(val *PasswordFeedbackOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordFeedbackOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordFeedbackOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordFeedbackOneOf1(val *PasswordFeedbackOneOf1) *NullablePasswordFeedbackOneOf1 {
	return &NullablePasswordFeedbackOneOf1{value: val, isSet: true}
}

func (v NullablePasswordFeedbackOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordFeedbackOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


